<a href="https://colab.research.google.com/github/shankarippar667-ai/Internship-Python-Codes/blob/main/11_july.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
a=list(range(20))
print(a)
for i in a :
  print(i**2,end=",")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
0,1,4,9,16,25,36,49,64,81,100,121,144,169,196,225,256,289,324,361,

In [8]:
a=list(range(20))
%timeit [i**2 for i in a]

1.24 µs ± 352 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
a=list(range(2000000))
%timeit [i**2 for i in a]

182 ms ± 29.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
a=list(range(20))
type(a)


list

In [13]:
b=np.array(range(0000000))
type(b)

numpy.ndarray

In [14]:
b.ndim

1

In [15]:
len(b)

0

In [16]:
b.shape

(0,)

In [17]:
a=[1,3,"sandip"]
print(type(a))
b=np.array(a)
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [18]:
b

array(['1', '3', 'sandip'], dtype='<U21')

In [32]:
a=np.arange(1,20)
print(a)
print(a[-2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
18


In [26]:
a[2:5]

array([3, 4, 5])

In [25]:
a[:3]

array([1, 2, 3])

In [33]:
#Multi-indexing
a[[2,5,7,15]]

array([ 3,  6,  8, 16])

In [34]:
a=np.array([6,9,3,5,7,2,8,1])
a<6

array([False, False,  True,  True, False,  True, False,  True])

In [35]:
a[a<6]

array([3, 5, 2, 1])

In [36]:
a[a%2==0]

array([6, 2, 8])

In [43]:
a=np.array(range(16))
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


In [46]:
b=a.reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])